name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzMwZjc0ZDctYzE5Ni00ZjBiLWJiMTItN2U1N2RhODk5MTE5IiwidGVuYW50X2lkIjoiMWJiYWMyMDM2Zjk0OTNiN2EzODA3ZDA4Y2QzNGZjZTA0ODE1M2RhYWQwYTE1OWYzNTNkMzY2YmQ1N2I5M2Q1NCIsImludGVybmFsX3NlY3JldCI6IjMyODI0YjEzLWQ4YTYtNGQ2Mi1iZjJlLWI4YjJkOGY5ZWVlOCJ9.H7JIatqZtLzKd4Oiz4SIeG1FX9hDaW4a-vO_h_b8-oI"
JWT_SECRET="secret@@@"